rabbitmq:
  image:
   tlodge/rabbitmq
  ports:
   - "5672:5672"
   - "15672"
  container_name:
   rabbitmq1

neo4j:
  image:
    tlodge/neo4j
  ports:
    - "7474"
  volumes: 
    - ~/dkrmnt/neo4j:/data/neo4j
  privileged: 
   true 
  container_name: 
   neo4j1
  command:
   /var/lib/neo4j/bin/neo4j console

postfix:
  image:
    tlodge/postfix
  ports:
    - "25"
  hostname:
    buttonkit.com  
  volumes:
    - ~/dkrmnt/postfix/main.cf:/etc/postfix/main.cf
  container_name:
    postfix

mongo:
  image:
    tlodge/mongo
  ports:
    - "27017"
  volumes:
    - ~/dkrmnt/mongo:/data/mongo
  container_name:
    mongo1
  command: 
    mongod --smallfiles --dbpath "/data/mongo" 

redis:
  image: 
    tlodge/redis
  ports:
    - "6679"
  volumes:
    - ~/dkrmnt/redis:/data/redis
  container_name:
    redis1

red:
  image:
    tlodge/red
  links:
    - mongo
    - neo4j
  ports:
    - "1880"
  volumes:
    - ~/dkrmnt/red:/data/red
  container_name:
    red1

worker:
  image:
    tlodge/worker
  links:
    - rabbitmq
    - red
  volumes:
    - ~/dkrmnt/worker/config.js:/root/roomcast/roomcast.worker/config.js
  container_name:
    worker1

buttonkit:
   image:
     tlodge/buttonkit 
   links:
     - neo4j
     - mongo
     - red
     - redis
     - rabbitmq
     - postfix
   ports:
     - "8080"
   command:
     npm start 
   volumes:
     - '/var/run/docker.sock:/var/run/docker.sock'
     - ~/dkrmnt/buttonkit/config/config.js:/usr/src/app/js/config.js:ro
     - ~/dkrmnt/buttonkit/config/appconfig.js:/usr/src/app/js/appconfig.js:ro
     - ~/dkrmnt/red:/data/red
     - ~/dkrmnt/buttonkit/media:/usr/src/app/static/media
     - ~/dkrmnt/buttonkit/media/signatures:/usr/src/app/static/media/signatures
     - ~/dkrmnt/buttonkit/logs:/data/buttonkit/logs
     - ~/dkrmnt/buttonkit/app:/data/buttonkit/app
   container_name:
     buttonkit1


nginx:
  image:
    tlodge/nginx
  links:
    - neo4j
    - red
    - buttonkit
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ~/dkrmnt/nginx/default:/etc/nginx/sites-enabled/default:ro
    - ~/dkrmnt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
#    - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
  container_name:
    nginx1
